databases:
  - name: Ansar-Database
    databaseName: ansar_database
    user: ansar_database_user

services:
  - type: web
    name: Hello-React
    runtime: ruby
    buildCommand: "./bin/render-build.sh; bundle exec rails db:migrate"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false